<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Flarestack.D1/Flarestack.D1.csproj" />
    <ProjectReference Include="../../../src/Flarestack.Authentication/Flarestack.Authentication.csproj" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../Todo.ServiceDefaults/Todo.ServiceDefaults.csproj" /></ItemGroup>
</Project>
