<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flarestack.Email" /><PackageReference Include="Flarestack.D1" />
    <PackageReference Include="Flarestack.Authentication" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../Todo.Client/Todo.Client.csproj" /><ProjectReference Include="../Todo.ServiceDefaults/Todo.ServiceDefaults.csproj" /></ItemGroup>
</Project>
