<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Flarestack.D1" /><PackageReference Include="Flarestack.Authentication" /><ProjectReference Include="../../samples/Todo/Todo.Web/Todo.Web.csproj" />
  </ItemGroup>
</Project>
