<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><PackageReference Include="Aspire.Hosting" /><PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  <PrivateAssets>all</PrivateAssets>
</PackageReference></ItemGroup>
</Project>
